
services:
  asmetal2java:
    build:
      context: .
      dockerfile: Dockerfile
    image: isaacmaffeis/asmetal2java:latest
    volumes:
      - ./services/asmetal2java/input:/app/asmetal2java_codegen/input
      - ./services/evoservice/input:/app/asmetal2java_codegen/output

  evoservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: isaacmaffeis/evoservice:latest
    volumes:
      - ./services/evoservice/evosuite-files:/app/evosuite-files
      - ./services/evoservice/evosuite-report:/app/evosuite-report
      - ./services/evoservice/evosuite-tests:/app/evosuite-tests
      - ./services/evoservice/input:/app/input
      - ./services/evoservice/target:/app/target
      - ./services/evoservice/scripts/gen_evosuite.sh:/app/scripts/gen_evosuite.sh
      - ./services/evoservice/src:/app/src
      - ./services/evoservice/m2:/root/.m2
      - ./services/javaToAvalla/input:/app/output

  javatoavalla:
    build:
      context: .
      dockerfile: Dockerfile
    image: isaacmaffeis/javatoavalla:latest
    volumes:
      - ./services/javaToAvalla/input:/app/input
      - ./output:/app/output
