version: '3.8'

services:
  asmetal2java:
    build:
      context: .
      dockerfile: Dockerfile
    image: isaacmaffeis/asmetal2java:latest
    volumes:
      - ./input:/app/asmetal2java_codegen/input
      - ./evosuite/input:/app/asmetal2java_codegen/output

  evoservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: isaacmaffeis/evoservice:latest
    volumes:
      - ./evosuite/evosuite-files:/app/evosuite-files
      - ./evosuite/evosuite-report:/app/evosuite-report
      - ./evosuite/evosuite-tests:/app/evosuite-test
      - ./evosuite/input:/app/input
