
services:
  asmetal2java:
    build:
      context: .
      dockerfile: Dockerfile
    image: isaacmaffeis/asmetal2java:latest
    volumes:
      - ./input:/app/asmetal2java_codegen/input
      - ./evoservice/input:/app/asmetal2java_codegen/output

  evoservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: isaacmaffeis/evoservice:latest
    volumes:
      - ./evoservice/evosuite-files:/app/evosuite-files
      - ./evoservice/evosuite-report:/app/evosuite-report
      - ./evoservice/evosuite-tests:/app/evosuite-tests
      - ./evoservice/input:/app/input
      - ./evoservice/target:/app/target
      - ./evoservice/scripts/gen_evosuite.sh:/app/scripts/gen_evosuite.sh
